[package]
name = "POB-Anonymous-Voting"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.10.8"
structopt = "0.3.26"
tokio = { version = "1.39.2", features = ["full"] }
alloy = { version = "0.4", features = ["full", "rlp"] }
alloy-sol-types = "0.8.15"
